import streamlit as st
from datetime import datetime

# Language mapping for display
LANGUAGE_NAMES = {
    'en': '🇬🇧 English',
    'hi': '🇮🇳 Hindi',
    'es': '🇪🇸 Spanish',
    'fr': '🇫🇷 French',
    'de': '🇩🇪 German',
    'ja': '🇯🇵 Japanese',
    'ko': '🇰🇷 Korean',
    'zh': '🇨🇳 Chinese',
    'ar': '🇸🇦 Arabic',
    'ru': '🇷🇺 Russian',
    'pt': '🇵🇹 Portuguese',
    'it': '🇮🇹 Italian',
    'nl': '🇳🇱 Dutch',
    'pl': '🇵🇱 Polish',
    'tr': '🇹🇷 Turkish'
}

def export_to_markdown(original_text, translation, summary, meeting_title, meeting_date, detected_lang):
    """Export meeting minutes to markdown"""
    lang_name = LANGUAGE_NAMES.get(detected_lang, detected_lang.upper())
    
    markdown_content = f"""# {meeting_title}
**Date**: {meeting_date}
**Generated**: {datetime.now().strftime("%Y-%m-%d %H:%M:%S")}
**Original Language**: {lang_name}

---

{summary}

---

## 🌍 English Translation

{translation}

---

## 📝 Original Transcription ({lang_name})

{original_text}

---
*Generated by AI Meeting Minutes Auto-Summarizer (Multilingual)*
"""
    return markdown_content